"""Generated vertical blueprint helpers."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

from setup_os.quality import agent_dna
from setup_os.spec import AgentSpec


def create_agent_directories(output_dir: Path) -> None:
    for directory in [
        "agents",
        "memory/raw",
        "memory/structured",
        "memory/policy",
        "tools",
        "notifications",
        "scheduler",
        "config",
        "evolution",
        "audit",
        "deployment",
    ]:
        (output_dir / directory).mkdir(parents=True, exist_ok=True)


def write_agent_metadata(spec: AgentSpec, output_dir: Path, approval_required_for: list[str]) -> None:
    _write(
        output_dir / "config.json",
        json.dumps(
            {
                "name": spec.name,
                "slug": spec.slug,
                "mode": "advisory",
                "storage": spec.storage,
                "notifications": spec.notifications,
                "approval_required_for": approval_required_for,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )
    _write(
        output_dir / "agent_dna.json",
        json.dumps(agent_dna(spec), indent=2, sort_keys=True) + "\n",
    )


def generate_portfolio_blueprint(spec: AgentSpec, output_dir: Path) -> None:
    create_agent_directories(output_dir)
    (output_dir / "data").mkdir(parents=True, exist_ok=True)
    (output_dir / "reports").mkdir(parents=True, exist_ok=True)

    _write(
        output_dir / "README.md",
        f"""# {spec.name}

This is a local, alert-only Portfolio Manager Agent scaffold generated by Setup OS.

## v0 Scope

- read sample/local CSV holdings
- produce a Markdown daily report
- emit console-first recommendations
- keep broker credentials and trade execution out of scope
- preserve future changes as reviewable evolution proposals

## Commands

```bash
python report.py
```

## Safety

{_bullet_list(spec.safety)}
""",
    )

    write_agent_metadata(
        spec,
        output_dir,
        [
            "broker_connection",
            "trade_execution",
            "strategy_update",
            "external_action",
        ],
    )

    _write(
        output_dir / "data" / "holdings.csv",
        """symbol,name,quantity,price,cost_basis
VOO,Vanguard S&P 500 ETF,10,500.00,4700.00
VXUS,Vanguard Total International Stock ETF,20,62.00,1180.00
BND,Vanguard Total Bond Market ETF,15,73.00,1110.00
""",
    )

    _write(
        output_dir / "report.py",
        """from __future__ import annotations

import csv
from datetime import date
from datetime import datetime, timezone
import json
from pathlib import Path


ROOT = Path(__file__).parent
DATA_PATH = ROOT / "data" / "holdings.csv"
REPORT_PATH = ROOT / "reports" / "daily_report.md"
INBOX_PATH = ROOT / ".setup_os" / "notifications.jsonl"


def notify(title: str, body: str, severity: str = "info") -> None:
    print(f"NOTIFY[{severity}]: {title} - {body}")
    INBOX_PATH.parent.mkdir(parents=True, exist_ok=True)
    event = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source": "portfolio-manager-agent",
        "title": title,
        "body": body,
        "severity": severity,
        "status": "new",
    }
    with INBOX_PATH.open("a", encoding="utf-8") as file:
        file.write(json.dumps(event, sort_keys=True) + "\\n")


def load_holdings() -> list[dict[str, str]]:
    with DATA_PATH.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def main() -> int:
    holdings = load_holdings()
    total_value = sum(float(row["quantity"]) * float(row["price"]) for row in holdings)

    lines = [
        "# Daily Portfolio Report",
        "",
        f"Date: {date.today().isoformat()}",
        "",
        f"Total sample portfolio value: ${total_value:,.2f}",
        "",
        "## Holdings",
        "",
    ]

    for row in holdings:
        value = float(row["quantity"]) * float(row["price"])
        weight = value / total_value if total_value else 0
        lines.append(f"- {row['symbol']}: ${value:,.2f} ({weight:.1%})")

    lines.extend(
        [
            "",
            "## Console Notification",
            "",
            "Portfolio report generated. Review allocation drift before taking action.",
        ]
    )

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\\n".join(lines) + "\\n", encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    notify(
        "Portfolio report generated",
        "Manual review required before trades.",
        "info",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""",
    )


def generate_health_blueprint(spec: AgentSpec, output_dir: Path) -> None:
    create_agent_directories(output_dir)
    (output_dir / "data").mkdir(parents=True, exist_ok=True)
    (output_dir / "reports").mkdir(parents=True, exist_ok=True)

    _write(
        output_dir / "README.md",
        f"""# {spec.name}

This is a local, advisory Health OS scaffold generated by Setup OS.

## v0 Scope

- read sample/local health notes and habit logs
- produce a Markdown wellness report
- collect questions for clinician review
- avoid diagnosis, medication changes, or emergency handling
- preserve future changes as reviewable evolution proposals

## Commands

```bash
python report.py
```

## Safety

{_bullet_list(spec.safety)}
""",
    )

    write_agent_metadata(
        spec,
        output_dir,
        [
            "diagnosis",
            "medication_change",
            "medical_decision",
            "external_action",
        ],
    )

    _write(
        output_dir / "data" / "health_notes.csv",
        """date,category,note
2026-06-30,sleep,Slept 7 hours and woke up once.
2026-06-30,exercise,Walked 30 minutes.
2026-06-30,question,Ask clinician about recurring shoulder tightness.
""",
    )

    _write(
        output_dir / "report.py",
        """from __future__ import annotations

import csv
from datetime import date
from datetime import datetime, timezone
import json
from pathlib import Path


ROOT = Path(__file__).parent
DATA_PATH = ROOT / "data" / "health_notes.csv"
REPORT_PATH = ROOT / "reports" / "wellness_report.md"
INBOX_PATH = ROOT / ".setup_os" / "notifications.jsonl"


def notify(title: str, body: str, severity: str = "info") -> None:
    print(f"NOTIFY[{severity}]: {title} - {body}")
    INBOX_PATH.parent.mkdir(parents=True, exist_ok=True)
    event = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source": "health-os-agent",
        "title": title,
        "body": body,
        "severity": severity,
        "status": "new",
    }
    with INBOX_PATH.open("a", encoding="utf-8") as file:
        file.write(json.dumps(event, sort_keys=True) + "\\n")


def load_notes() -> list[dict[str, str]]:
    with DATA_PATH.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def main() -> int:
    notes = load_notes()
    questions = [row for row in notes if row["category"] == "question"]

    lines = [
        "# Daily Wellness Report",
        "",
        f"Date: {date.today().isoformat()}",
        "",
        "This report is advisory and is not medical advice.",
        "",
        "## Notes",
        "",
    ]

    for row in notes:
        lines.append(f"- {row['date']} [{row['category']}]: {row['note']}")

    lines.extend(["", "## Questions For Clinician", ""])
    if questions:
        for row in questions:
            lines.append(f"- {row['note']}")
    else:
        lines.append("- None recorded.")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\\n".join(lines) + "\\n", encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    notify(
        "Wellness report generated",
        "Review notes and clinician questions. This is not medical advice.",
        "info",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""",
    )


def _write(path: Path, content: str) -> None:
    path.write_text(dedent(content).lstrip(), encoding="utf-8")


def _bullet_list(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)
